language: objective-c
osx_image: xcode7
cache:
  directories:
  - vendor/bundle
  - Pods

env:
  global:
    secure: aPU99rsISEo4CwVBenahzI90IdXXbOiLiL46K7qrWbpXAOQQG0b2/VzfTmZRR0W23ilLWJjrTcgXEwcvn3KE9vPQQUt66+hpjoD79xQwkIelBcxYQbUaYQbWjBHrB4ueBjkrf4LGdVMqlGqCXOw64OS0xfKuXznA38ddnjshkPQ=

before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- echo "machine github.com login $GITHUB_API_KEY" > ~/.netrc
- chmod 600 ~/.netrc

install:
 - bundle install --without=deployment --deployment --jobs=3 --retry=3
 - make ci_keys
 - bundle exec pod install

script:
- make test

after_success: bundle exec slather
notifications:
  slack: artsy:9hT8HcywAEZV7dJrbSNGcR6u
